version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx:/etc/nginx/conf.d"
      - "./data:/var/www/html"
      - "./nginx/log:/var/log/nginx"
    environment:
      TZ: "Asia/Tokyo"
  logstash:
    image: docker.elastic.co/logstash/logstash:6.5.2
    ports:
      - "5044:5044"
      - "9600:9600"
    links:
      - elasticsearch
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - "./nginx/log:/var/log/nginx/"
      - "./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf"
      - "./logstash/log:/var/log/logstash/"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.2
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.2
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200

